version: "3"
services:
  tomcat:
    image: tomcat:9.0.39
    ports: 
      - 8888:8080
    # stdin_open: true 
    # tty: true
    volumes: 
      - tomcatConfig/usr/local/tomcat/conf
      - ./tomcatHome:tomcatConfig
volumes: 
  tomcatConfig: