version: "3"
services:
  nginx:
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
  question-bank:
    build: 
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    volumes:
      - ./QuestionBankBackend/logs:/app/logs
    deploy:
      replicas: 2
  react:
    build:
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
        API_END_POINT: jordanleeeee
    environment:
      - NODE_ENV=production
      - API_END_POINT=jordanleeeee
  filebeat:
    build: ./filebeat
    volumes:
      - ./nginxlog/logs:/var/log/nginx:ro
    depends_on:
      - nginx
      - kibana
      - elasticsearch
  elasticsearch:
    ports:
      - 9200:9200
      - 9300:9300
    environment: 
      - discovery.type=single-node
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
  kibana:
    ports:
      - 5601:5601
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 
    image: docker.elastic.co/kibana/kibana:7.13.2
    depends_on: 
      - elasticsearch