version: "3"
services:
  nginx:
    ports:
      - "80:80"
    image: nginx:stable-alpine
    volumes:
      - ./nginx/staticSite.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/static:/usr/share/nginx/html/