version: "3"
services:
  nginx:
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
  question-bank:
    ports:
      - "3030:3030"
    build: 
      args:
        NODE_ENV: development
    volumes:
      - ./QuestionBankBackend:/app
      - ./QuestionBankBackend/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
  react:
    build:
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./ReactQuestionBank:/app
      - ./ReactQuestionBank/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  spider:
    ports:
      - 3040:3040
    volumes: 
      - ./WebImageCrawler:/usr/src/app
    command: python rest.py --mode=development
    tty: true